FROM golang:1.20.3
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
RUN go install github.com/swaggo/swag/cmd/swag@latest
COPY . ./
EXPOSE 8787
CMD sleep 10000
# CMD swag init && go run main.go
# CMD go run main.go
