version: '3'
services:
  api:
    container_name: 'go-api'
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - 80:8787
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: todos
      MYSQL_ROOT_PASSWORD: example
